export const API_ENDPOINTS = {
  AUTH_LOGIN: "/auth/login",
  AUTH_SIGNUP: "/auth/signup",
  USERS_ME: "/users/me",
  USERS_ME_ADDRESSES: "/users/me/addresses",
  USERS_ME_ADDRESS_BY_ID: (addressId) => `/users/me/addresses/${addressId}`,
  USERS_ME_ADDRESS_DEFAULT: (addressId) => `/users/me/addresses/${addressId}/default`,
  PRODUCTS: "/products",
  PRODUCT_CATEGORIES: "/products/categories",
  PRODUCT_BY_ID: (id) => `/products/${id}`,
  REVIEWS_BY_PRODUCT: (productId) => `/reviews/product/${productId}`,
  REVIEW_VENDOR_RESPONSE: (reviewId) => `/reviews/${reviewId}/vendor-response`,
  ORDERS: "/orders",
  ORDERS_VENDOR_REPORT: "/orders/vendor/report",
  ORDER_STATUS_BY_ID: (id) => `/orders/${id}/status`,
  CONVERSATIONS: "/conversations",
  MESSAGES: "/messages",
  MESSAGES_BY_CONVERSATION: (conversationId) => `/messages/${conversationId}`,
  MARK_MESSAGES_READ: (conversationId) => `/messages/read/${conversationId}`,
  PAYMENTS_CREATE: "/payments/create",
  PAYMENTS_VERIFY_RAZORPAY: "/payments/verify-razorpay",
  PAYMENTS_UPI_GENERATE: "/payments/upi/generate",
  PAYMENTS_STATUS: (orderId) => `/payments/status/${orderId}`,
  PAYMENTS_COD: "/payments/cod",
};
