export const API_ENDPOINTS = {
  AUTH_LOGIN: "/auth/login",
  AUTH_SIGNUP: "/auth/signup",
  AUTH_FORGOT_PASSWORD: "/auth/forgot-password",
  AUTH_RESET_PASSWORD: "/auth/reset-password",
  AUTH_SOCIAL_LOGIN: "/auth/social-login",
  USERS_ME: "/users/me",
  USERS_ME_ADDRESSES: "/users/me/addresses",
  USERS_ME_ADDRESS_BY_ID: (addressId) => `/users/me/addresses/${addressId}`,
  USERS_ME_ADDRESS_DEFAULT: (addressId) => `/users/me/addresses/${addressId}/default`,
  USERS_ME_WISHLIST: "/users/me/wishlist",
  USERS_ME_WISHLIST_BY_ID: (productId) => `/users/me/wishlist/${productId}`,
  USERS_ME_RECENTLY_VIEWED: "/users/me/recently-viewed",
  USERS_ME_RECENTLY_VIEWED_BY_ID: (productId) => `/users/me/recently-viewed/${productId}`,
  USERS_ME_SELLER_PROFILE: "/users/me/seller-profile",
  PRODUCTS: "/products",
  PRODUCT_CATEGORIES: "/products/categories",
  PRODUCT_BY_ID: (id) => `/products/${id}`,
  REVIEWS_BY_PRODUCT: (productId) => `/reviews/product/${productId}`,
  REVIEW_VENDOR_RESPONSE: (reviewId) => `/reviews/${reviewId}/vendor-response`,
  ORDERS: "/orders",
  ORDERS_VENDOR_REPORT: "/orders/vendor/report",
  ORDER_STATUS_BY_ID: (id) => `/orders/${id}/status`,
  CONVERSATIONS: "/conversations",
  MESSAGES: "/messages",
  MESSAGES_BY_CONVERSATION: (conversationId) => `/messages/${conversationId}`,
  MARK_MESSAGES_READ: (conversationId) => `/messages/read/${conversationId}`,
  PAYMENTS_CREATE: "/payments/create",
  PAYMENTS_VERIFY_RAZORPAY: "/payments/verify-razorpay",
  PAYMENTS_UPI_GENERATE: "/payments/upi/generate",
  PAYMENTS_STATUS: (orderId) => `/payments/status/${orderId}`,
  PAYMENTS_COD: "/payments/cod",
  ORDER_CANCEL: (id) => `/orders/${id}/cancel`,
  ORDER_REORDER: (id) => `/orders/${id}/reorder`,
  ORDER_TRACKING: (id) => `/orders/${id}/tracking`,
  RETURNS: "/returns",
  RETURNS_MINE: "/returns/mine",
  RETURNS_VENDOR: "/returns/vendor",
  RETURN_STATUS_BY_ID: (id) => `/returns/${id}/status`,
  PROMOTIONS_ACTIVE: "/promotions/active",
  PROMOTIONS_VALIDATE: "/promotions/validate",
  PROMOTIONS: "/promotions",
  PROMOTIONS_MINE: "/promotions/mine",
  PROMOTION_BY_ID: (id) => `/promotions/${id}`,
  PROMOTION_TOGGLE_BY_ID: (id) => `/promotions/${id}/toggle`,
  FINANCE_SUMMARY: "/finance/summary",
  FINANCE_TRANSACTIONS: "/finance/transactions",
  FINANCE_PAYOUTS: "/finance/payouts",
  FINANCE_PAYOUT_REQUEST: "/finance/payouts/request",
  FINANCE_TAX_REPORT: "/finance/tax-report",
};
